export const CHARITY_TRANSACTIONS_COLUMN_HEADER = {
  checkbox: {
    id: '0',
    fieldName: 'srno',
    colDisplayName: '',
    colType: 'checkbox',
    userIndex: 0,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  srno: {
    userIndex: 1,
    fieldName: 'srno',
    colDisplayName: 'Trans Id',
    title: 'Transaction Id',
    widthOfColumn: 75,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  charityname: {
    userIndex: 2,
    fieldName: 'charityname',
    colDisplayName: 'Charity Name',
    title: 'Charity Name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  orgid: {
    userIndex: 3,
    fieldName: 'orgid',
    colDisplayName: 'Org Id',
    title: 'Org Id',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  finyearid: {
    userIndex: 4,
    fieldName: 'finyearid',
    colDisplayName: 'Fin Year',
    title: 'Financial Year',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  suggested_amount: {
    userIndex: 5,
    fieldName: 'suggested_amount',
    colDisplayName: 'Suggested Amt',
    title: 'Suggested Amount',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  amount: {
    userIndex: 6,
    fieldName: 'amount',
    colDisplayName: 'Amount',
    title: 'Amount',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  amount_in_words: {
    userIndex: 7,
    fieldName: 'amount_in_words',
    colDisplayName: 'Amt in words',
    title: 'Amount in Words',
    widthOfColumn: 200,
    colType: 'text',
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  modeofpay: {
    userIndex: 8,
    fieldName: 'modeofpay',
    colDisplayName: 'Mod of Pay',
    title: 'Mode of Pay',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  paidvia_cc: {
    userIndex: 9,
    fieldName: 'paidvia_cc',
    colDisplayName: 'Paid Via CC',
    title: 'Paid Via CC',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  paid_from: {
    userIndex: 10,
    fieldName: 'paid_from',
    colDisplayName: 'Paid From',
    title: 'Paid From',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  irs_ok: {
    userIndex: 11,
    fieldName: 'irs_ok',
    colDisplayName: 'IRS OK',
    title: 'IRS OK',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  receipt: {
    userIndex: 12,
    fieldName: 'receipt',
    colDisplayName: 'Receipt',
    title: 'Receipt',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  receipt_quicken: {
    userIndex: 13,
    fieldName: 'receipt_quicken',
    colDisplayName: 'Receipt Quicken',
    title: 'Receipt Quicken',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  direction_of: {
    userIndex: 14,
    fieldName: 'direction_of',
    colDisplayName: 'Direction Of',
    title: 'Direction Of',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  wording_direction: {
    userIndex: 15,
    fieldName: 'wording_direction',
    colDisplayName: 'Wording Direction',
    title: 'Wording Direction',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  courties_copies: {
    userIndex: 16,
    fieldName: 'courties_copies',
    colDisplayName: 'Countries Copies',
    title: 'Countries Copies',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  transmite_date: {
    userIndex: 17,
    fieldName: 'transmite_date',
    colDisplayName: 'Transmite Date',
    title: 'Transmite Date',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '17',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  createdate: {
    userIndex: 18,
    fieldName: 'createdate',
    colDisplayName: 'Created Date',
    title: 'Created Date',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '18',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  createdby: {
    userIndex: 19,
    fieldName: 'createdby',
    colDisplayName: 'Created By',
    title: 'Created By',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '19',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  remarks: {
    userIndex: 20,
    fieldName: 'remarks',
    colDisplayName: 'Created By',
    title: 'Created By',
    widthOfColumn: 100,
    colType: 'text',
    dataType: 'text',
    id: '20',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
