export const CHARITY_MASTER_COLUMN_HEADER = {
  checkbox: {
    id: '0',
    fieldName: 'charityid',
    colDisplayName: '',
    colType: 'checkbox',
    userIndex: 0,
    imgName: '',
    tooltipSrc: '',
    dataType: 'checkbox',
    function: '',
    funParams: '',
    wrapData: '',
    widthOfColumn: 35,
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  charityname: {
    userIndex: 1,
    fieldName: 'charityname',
    colDisplayName: 'Charity Name',
    title: 'Charity Name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '1',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  ein: {
    userIndex: 2,
    fieldName: 'ein',
    colDisplayName: 'EIN',
    title: 'EIN',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '2',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  contactname: {
    userIndex: 3,
    fieldName: 'contactname',
    colDisplayName: 'Contact Name',
    title: 'Contact Name',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '3',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  dearwhom: {
    userIndex: 4,
    fieldName: 'dearwhom',
    colDisplayName: 'Dear Whom',
    title: 'Dear Whom',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '4',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  address1: {
    userIndex: 5,
    fieldName: 'address1',
    colDisplayName: 'Address 1',
    title: 'Address 1',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '5',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  address2: {
    userIndex: 6,
    fieldName: 'address2',
    colDisplayName: 'Address 2',
    title: 'Address 2',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '6',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  city: {
    userIndex: 7,
    fieldName: 'city',
    colDisplayName: 'City',
    title: 'City',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '7',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  postalcode: {
    userIndex: 8,
    fieldName: 'postalcode',
    colDisplayName: 'Postal Code',
    title: 'Postal Code',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '8',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emailid1: {
    userIndex: 9,
    fieldName: 'emailid1',
    colDisplayName: 'Email ID 1',
    title: 'Email ID 1',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '9',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  emailid2: {
    userIndex: 10,
    fieldName: 'emailid2',
    colDisplayName: 'Email ID 2',
    title: 'Email ID 2',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '10',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  phone1: {
    userIndex: 11,
    fieldName: 'phone1',
    colDisplayName: 'Phone No 1',
    title: 'Phone No 1',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '11',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  phone2: {
    userIndex: 12,
    fieldName: 'phone2',
    colDisplayName: 'Phone No 2',
    title: 'Phone No 2',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '12',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  url: {
    userIndex: 13,
    fieldName: 'url',
    colDisplayName: 'URL',
    title: 'URL',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '13',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  active: {
    userIndex: 14,
    fieldName: 'active',
    colDisplayName: 'Active',
    title: 'Active',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '14',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  remarks: {
    userIndex: 15,
    fieldName: 'remarks',
    colDisplayName: 'Remarks',
    title: 'Remarks',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '15',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  },
  createdby: {
    userIndex: 16,
    fieldName: 'createdby',
    colDisplayName: 'Created By',
    title: 'Created By',
    widthOfColumn: 150,
    colType: 'text',
    dataType: 'text',
    id: '16',
    imgName: '',
    tooltipSrc: '',
    function: '',
    funParams: '',
    wrapData: '',
    isSortSupported: false,
    isCustomAttributeColumn: false
  }
};
