
export const AppConstant = {

  CHARITY_MASTER_APP_TYPE: 1,
  CHARITY_TRANSACTIONS_APP_TYPE: 2,

  CHARITY_MASTER_LISTING_TYPE: 1,
  CHARITY_TRANSACTIONS_LISTING_TYPE: 2,

  FILE_TRANSMITTAL_LISTING: 0,
  APPS_TRANSMITTAL_LISTING: 0,

  GET_USER_SEARCH_FILTERS_COLUMNS: 0,
  DISCUSSION_LISTING: 0,
  SAVE_SORT_DETAILS_FOR_USER: 0,

  DROPDOWN_BROADCAST_STRING: {
    DD_CLOSE: 'DD_CLOSE',
    DD_OPEN: 'DD_OPEN',
    DD_DESTROY: 'DD_DESTROY',
    DD_CHANGED: 'DD_CHANGED',
  },

  FIRST_MEETING_MOM: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_MOM'
  },

  FEASIBILITY_SURVEY: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_FEA_SURVEY'
  },

  CHARITY_MASTER: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT'
  },

  CHARITY_TRANSACTIONS: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_CHARITY_TRANSACTIONS'
  },

  PRELIMINARY_DESIGN: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_PRELIMINARY_DESIGN'
  },

  TECHNO_COMMERCIAL_FEASIBILITY: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_TECHNO_COMMERCIAL_FEASIBILITY'
  },
  FACT_SHEET: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_FACT_SHEET'
  },

  SITE_KICK_OF_MEETING: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_SITE_KICK_OF_MEETING'
  },

  PROPOSAL_REVIEW_MEETING: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_PROPOSAL_REVIEW_MEETING'
  },
  VENDOR_ALLOCATION: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_VENDOR_ALLOCATION'
  },
  ENGINEER_ALLOCATION: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_ENGINEER_ALLOCATION'
  },

  PPA_EXECUTION: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_PPA_EXECUTION'
  },

  JOINT_SURVEY_REPORT: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_JOINT_SURVEY_REPORT'
  },

  DAILY_PROGRESS_REPORT: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_DAILY_PROGRESS_REPORT'
  },

  INSTALLATION_ACTIVITIES: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_INSTALLATION_ACTIVITIES'
  },

  FIRST_MEETING_STATUS: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_FIRST_MEETING_STATUS'
  },
  BOM: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_BOM'
  },
  USERS: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_USERS'
  },

  PPA_SUMMARY: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_PPA_SUMMARY'
  },

  DIGITAL_SURVEY: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_DIGITAL_SURVEY'
  },

  PRELIMINARY_PROPOSAL_PRESENTATION: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_PRELIMINARY_PROPOSAL_PRESENTATION'
  },
  TERM_SHEET: {
    LOAD_DATA_FOR_EDIT: 'LOAD_DATA_FOR_EDIT_TERM_SHEET'
  },
};
